import type { VideoStyle } from './types.js';
export const videoStyles: VideoStyle[] = [
  {
    id: 'paper',
    name: '暖纸手账',
    tag: '温柔 · 日常',
    background: '#f5ecda',
    accent: '#8f644b',
    ink: '#352f29',
    paper: '#fffaf0',
    transition: 'fade',
    defaultMusicId: 'carefree',
    secondMusicId: 'life-of-riley',
  },
  {
    id: 'minimal',
    name: '清晨极简',
    tag: '清透 · 钢琴',
    background: '#f4f5f0',
    accent: '#607c79',
    ink: '#24312f',
    paper: '#ffffff',
    transition: 'smoothup',
    defaultMusicId: 'morning',
    secondMusicId: 'bright-wish',
  },
  {
    id: 'forest',
    name: '森系清新',
    tag: '自然 · 松弛',
    background: '#e7efe4',
    accent: '#53795d',
    ink: '#283d30',
    paper: '#fafbf4',
    transition: 'fade',
    defaultMusicId: 'laid-back-guitars',
    secondMusicId: 'folk-round',
  },
  {
    id: 'postcard',
    name: '旅行明信片',
    tag: '假日 · 轻快',
    background: '#e8f0f4',
    accent: '#be6749',
    ink: '#284453',
    paper: '#fffaf0',
    transition: 'slideleft',
    defaultMusicId: 'beachfront-celebration',
    secondMusicId: 'casa-bossa-nova',
  },
  {
    id: 'polaroid',
    name: '拍立得相册',
    tag: '相册 · 怀旧',
    background: '#e9dfd4',
    accent: '#956b69',
    ink: '#4a3538',
    paper: '#ffffff',
    transition: 'smoothright',
    defaultMusicId: 'daily-beetle',
    secondMusicId: 'easy-lemon',
  },
  {
    id: 'film',
    name: '复古胶片',
    tag: '复古 · 爵士',
    background: '#372e28',
    accent: '#d4ac78',
    ink: '#f1dec0',
    paper: '#534239',
    transition: 'dissolve',
    defaultMusicId: 'bossa-antigua',
    secondMusicId: 'local-forecast',
  },
  {
    id: 'cinema',
    name: '黑白电影',
    tag: '电影 · 叙事',
    background: '#17191c',
    accent: '#d8dbe0',
    ink: '#f4f4f4',
    paper: '#26292d',
    transition: 'fadeblack',
    defaultMusicId: 'dreams-become-real',
    secondMusicId: 'long-road-ahead',
  },
  {
    id: 'night',
    name: '夜色留白',
    tag: '安静 · 夜晚',
    background: '#121d38',
    accent: '#b0bbdf',
    ink: '#edf0fa',
    paper: '#21314f',
    transition: 'fade',
    defaultMusicId: 'at-rest',
    secondMusicId: 'moonlight-hall',
  },
  {
    id: 'candy',
    name: '糖果派对',
    tag: '明亮 · 活泼',
    background: '#ffe7ed',
    accent: '#ba426d',
    ink: '#632944',
    paper: '#fff9ce',
    transition: 'circleopen',
    defaultMusicId: 'monkeys-spinning-monkeys',
    secondMusicId: 'fluffing-a-duck',
  },
  {
    id: 'comic',
    name: '漫画日常',
    tag: '俏皮 · 趣味',
    background: '#ffe178',
    accent: '#262b37',
    ink: '#222531',
    paper: '#fffef6',
    transition: 'wipeleft',
    defaultMusicId: 'sneaky-snitch',
    secondMusicId: 'investigations',
  },
  {
    id: 'neon',
    name: '霓虹都市',
    tag: '电子 · 都市',
    background: '#111226',
    accent: '#73e5de',
    ink: '#f2eeff',
    paper: '#24213d',
    transition: 'smoothleft',
    defaultMusicId: 'cipher',
    secondMusicId: 'neon-laser-horizon',
  },
  {
    id: 'pixel',
    name: '像素游戏',
    tag: '游戏 · 冒险',
    background: '#25284c',
    accent: '#8eedb2',
    ink: '#f7f0d8',
    paper: '#3b3f64',
    transition: 'pixelize',
    defaultMusicId: 'bit-quest',
    secondMusicId: 'bit-shift',
  },
];
